[tasks.run]
workspace = false
command = "cargo"
args = ["run"]
dependencies = ["build"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
workspace = false
dependencies = ["format", "image-build"]

# also build kernel
[tasks.image-build]
workspace = false
command = "cargo"
args = ["build"]
dependencies = ["init-build"]

[tasks.init-build]
workspace = false
cwd = "./init"
command = "cargo"
args = ["build"]
dependencies = ["vfs-server-build", "process-server-build"]

[tasks.vfs-server-build]
workspace = false
cwd = "./vfs-server"
command = "cargo"
args = ["build"]

[tasks.process-server-build]
workspace = false
cwd = "./process-server"
command = "cargo"
args = ["build"]

[tasks.default]
alias = "run"