[env]
MTI_FUN_OS_KERNEL_PROFILE = "release" # or dev
MTI_FUN_OS_KERNEL_TARGET = "x86_64-unknown-none"
MTI_FUN_OS_INIT_PROFILE = "release"
MTI_FUN_OS_INIT_TARGET = "x86_64-mti-fun-os-init"
MTI_FUN_OS_SERVERS_PROFILE = "release"
MTI_FUN_OS_SERVERS_TARGET = "x86_64-mti_fun_os"

[tasks.run]
workspace = false
command = "cargo"
args = ["run", "--profile", "${MTI_FUN_OS_KERNEL_PROFILE}"]
dependencies = ["build"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
workspace = false
dependencies = ["format", "image-build"]

# also build kernel
[tasks.image-build]
workspace = false
command = "cargo"
args = ["build", "--profile", "${MTI_FUN_OS_KERNEL_PROFILE}"]
dependencies = ["init-build"]

[tasks.init-build]
workspace = false
cwd = "./init"
command = "cargo"
args = ["build", "--profile", "${MTI_FUN_OS_INIT_PROFILE}"]
dependencies = ["vfs-server-build", "process-server-build"]

[tasks.vfs-server-build]
workspace = false
cwd = "./servers/vfs-server"
command = "cargo"
args = ["build", "--profile", "${MTI_FUN_OS_SERVERS_PROFILE}"]

[tasks.process-server-build]
workspace = false
cwd = "./servers/process-server"
command = "cargo"
args = ["build", "--profile", "${MTI_FUN_OS_SERVERS_PROFILE}"]

[tasks.default]
alias = "run"