[build]
target="x86_64-mti_fun_os-init.json"
rustflags = ["-C", "link-args=-T../../../init/linker.ld", "-C", "force-frame-pointers"]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]